[package]
name = "check-pr"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.89"
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"
structopt = "0.3.26"
